package librarymanagementsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author vugar
 */
public class ManageBooks extends javax.swing.JFrame {
    
DefaultTableModel mod;
    /**
     * Creates new form ManageStudents
     */
    public ManageBooks() {
        initComponents();
        setLocationRelativeTo(null);
        setBooksTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbFirstName = new javax.swing.JLabel();
        tfBookName = new javax.swing.JTextField();
        lbLastName = new javax.swing.JLabel();
        tfAuthorName = new javax.swing.JTextField();
        lbDepartment = new javax.swing.JLabel();
        tfBookID = new javax.swing.JTextField();
        lbStudentID = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfQuantity = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableBooks = new rojeru_san.complementos.RSTableMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Manage Books");

        lbFirstName.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 18)); // NOI18N
        lbFirstName.setForeground(new java.awt.Color(255, 255, 255));
        lbFirstName.setText("Book Name");

        tfBookName.setForeground(new java.awt.Color(0, 0, 0));

        lbLastName.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 18)); // NOI18N
        lbLastName.setForeground(new java.awt.Color(255, 255, 255));
        lbLastName.setText("Author Name");

        tfAuthorName.setForeground(new java.awt.Color(0, 0, 0));

        lbDepartment.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 18)); // NOI18N
        lbDepartment.setForeground(new java.awt.Color(255, 255, 255));
        lbDepartment.setText("Quantity");

        tfBookID.setForeground(new java.awt.Color(0, 0, 0));
        tfBookID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBookIDActionPerformed(evt);
            }
        });

        lbStudentID.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 18)); // NOI18N
        lbStudentID.setForeground(new java.awt.Color(255, 255, 255));
        lbStudentID.setText("Book ID");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementsystem/icons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        tfQuantity.setForeground(new java.awt.Color(0, 0, 0));

        btnAdd.setForeground(new java.awt.Color(0, 0, 0));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbStudentID, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbFirstName, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbDepartment)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tfBookName, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lbLastName)
                                    .addGap(145, 145, 145)
                                    .addComponent(tfAuthorName, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(tfBookID, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(207, 207, 207)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbStudentID)
                    .addComponent(tfBookID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFirstName)
                    .addComponent(tfBookName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLastName)
                    .addComponent(tfAuthorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDepartment)
                    .addComponent(tfQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 351, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(69, 69, 69))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        tableBooks.setBackground(new java.awt.Color(0, 0, 0));
        tableBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book_id", "Name", "Category", "Publisher"
            }
        ));
        tableBooks.setColorBackgoundHead(new java.awt.Color(102, 0, 0));
        tableBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBooksMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableBooks);
        tableBooks.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(288, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(222, 222, 222))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(364, 364, 364)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(576, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 1330, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeAdminPage().setVisible(true);
            }
        }
            );
    }//GEN-LAST:event_jLabel7MouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try{
        int bookID = Integer.parseInt(tfBookID.getText());
        String bookName = tfBookName.getText();
        String authorName = tfAuthorName.getText();
        int quantity = Integer.parseInt(tfQuantity.getText());
        
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(databaseConnection,databaseUsername,databasePassword);
            
            String query = "insert into books values("+bookID+", '"+bookName+"', '"+authorName+"', '"+quantity+"');";
            Statement st = con.createStatement();
            st.executeUpdate(query);
            JOptionPane.showMessageDialog(this, "The book has been added!");
            
            con.close();
            tfBookID.setText("");
            tfBookName.setText("");
            tfAuthorName.setText("");
            
            tfQuantity.setText("");
            mod = (DefaultTableModel) tableBooks.getModel();
            mod.setRowCount(0);
            setBooksTable();
            
            
            
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            int bookID = Integer.parseInt(tfBookID.getText());
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(databaseConnection,databaseUsername,databasePassword);
            String query = "delete from books where book_id ="+bookID+" ;";
            Statement st = con.createStatement();
            st.executeUpdate(query);
            JOptionPane.showMessageDialog(this, "The book has been deleted!");
            tfBookID.setText("");
            tfBookName.setText("");
            tfAuthorName.setText("");
            tfQuantity.setText("");
            
            mod.setRowCount(0);
            setBooksTable();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
        int bookID = Integer.parseInt(tfBookID.getText());
        String bookName = tfBookName.getText();
        String authorName = tfAuthorName.getText();
        int quantity = Integer.parseInt(tfQuantity.getText());
        
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(databaseConnection,databaseUsername,databasePassword);
            
            String query = "update books set book_name = '"+bookName+"', author = '"+authorName+"', quantity = '"+quantity+"' where book_id = '"+bookID+"';";
            Statement st = con.createStatement();
            st.executeUpdate(query);
            JOptionPane.showMessageDialog(this, "The book has been added!");
            
            con.close();
            tfBookID.setText("");
            tfBookName.setText("");
            tfAuthorName.setText("");
            
            tfQuantity.setText("");
            mod = (DefaultTableModel) tableBooks.getModel();
            mod.setRowCount(0);
            setBooksTable();
            
            
            
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tfBookIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBookIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBookIDActionPerformed

    private void tableBooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBooksMouseClicked
        int selectedRow = tableBooks.getSelectedRow();
        TableModel mod = tableBooks.getModel();
        
        tfBookID.setText(mod.getValueAt(selectedRow, 0).toString());
        tfBookName.setText(mod.getValueAt(selectedRow, 1).toString());
        tfAuthorName.setText(mod.getValueAt(selectedRow, 2).toString());
        tfQuantity.setText(mod.getValueAt(selectedRow, 3).toString());
      
    }//GEN-LAST:event_tableBooksMouseClicked

    /**
     * @param args the command line arguments
     */
    
  public void setBooksTable(){
    try{
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection(databaseConnection,databaseUsername,databasePassword);
        Statement st = con.createStatement();
        String query = "select * from books;";
        ResultSet rs = st.executeQuery(query);
        while(rs.next()){
        String bookID = rs.getString("book_id");
        String bookName = rs.getString("book_name");
        String author = rs.getString("author");
        String quantity = rs.getString("quantity");
        
        
        Object[] obj = {bookID,bookName,author,quantity};
        mod = (DefaultTableModel) tableBooks.getModel();
        mod.addRow(obj);
        }
        
        }
        catch(Exception e)
        {System.out.println(e.getMessage());
        }
    }
    String databaseConnection = "jdbc:mysql://localhost:3306/library?zeroDateTimeBehavior=CONVERT_TO_NULL";
    String databaseUsername = "root";
    String databasePassword = "Vusala7677";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbDepartment;
    private javax.swing.JLabel lbFirstName;
    private javax.swing.JLabel lbLastName;
    private javax.swing.JLabel lbStudentID;
    private rojeru_san.complementos.RSTableMetro tableBooks;
    private javax.swing.JTextField tfAuthorName;
    private javax.swing.JTextField tfBookID;
    private javax.swing.JTextField tfBookName;
    private javax.swing.JTextField tfQuantity;
    // End of variables declaration//GEN-END:variables
}
